services:
  frontend:
    build: .
    image: movie-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_MOVIE_API_BASE_URL=http://backend:3001/api
      - MOVIE_API_KEY=movie_api_key
    restart: unless-stopped
    networks:
      - movie-network

  backend:
    build: ../movie-back-end
    image: movie-backend:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - GLOBAL_PREFIX=api
      - RAPID_URL=https://streaming-availability.p.rapidapi.com
      - API_KEY=movie_api_key
      - RAPID_API_KEY=${RAPID_API_KEY}
    restart: unless-stopped
    networks:
      - movie-network

networks:
  movie-network:
    driver: bridge